export const GET_ROOMS = "GET_ROOMS";
export const GET_SINGLE_ROOM = "GET_SINGLE_ROOM";
export const GET_FEATURED_ROOMS = "GET_FEATURED_ROOMS";

export const SORT_ROOMS = "SORT_ROOMS";
export const TYPE_FILTER = "TYPE_FILTER";
export const CAPACITY_FILTER = "CAPACITY_FILTER";
export const PRICE_FILTER = "PRICE_FILTER";
export const MIN_SIZE_FILTER = "MIN_SIZE_FILTER";
export const MAX_SIZE_FILTER = "MAX_SIZE_FILTER";
export const BREAKFAST_FILTER = "BREAKFAST_FILTER";
export const PETS_FILTER = "PETS_FILTER";
